"""initial schema

Revision ID: ed438171a236
Revises: 
Create Date: 2026-08-04 16:19:00.102464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed438171a236'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.Enum('API', 'SCRAPER', 'UPLOAD', name='sourcetype'), nullable=False),
    sa.Column('reference_url', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('metric_type', sa.Enum('JOB_POSTINGS_COUNT', 'AVG_SALARY', 'UNEMPLOYMENT_RATE', 'SECTOR_GROWTH_RATE', name='metrictype'), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('role_category', sa.String(length=100), nullable=True),
    sa.Column('horizon', sa.Enum('ONE_MONTH', 'THREE_MONTHS', 'ONE_YEAR', name='horizon'), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence_low', sa.Float(), nullable=True),
    sa.Column('confidence_high', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('based_on_period_start', sa.Date(), nullable=False),
    sa.Column('based_on_period_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_data_points',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.Enum('JOB_POSTINGS_COUNT', 'AVG_SALARY', 'UNEMPLOYMENT_RATE', 'SECTOR_GROWTH_RATE', name='metrictype'), nullable=False),
    sa.Column('region', sa.String(length=55), nullable=False),
    sa.Column('sector', sa.String(length=55), nullable=True),
    sa.Column('role_category', sa.String(length=55), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_filename', sa.String(length=100), nullable=True),
    sa.Column('original_file_storage_key', sa.String(length=100), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('current_role', sa.String(length=100), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_paths',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('declining_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rising_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_path', sa.Text(), nullable=False),
    sa.Column('based_on_forecast_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('based_on_signal_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_signals',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('relevance', sa.String(length=255), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('based_on_signal_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggered_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trend_alerts')
    op.drop_table('market_signals')
    op.drop_table('career_paths')
    op.drop_table('user_profiles')
    op.drop_table('market_data_points')
    op.drop_table('forecasts')
    op.drop_table('users')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
